spring.application.name=hotel
spring.datasource.driver=jdbc:postgresql://localhost:5432/HotelRoom
spring.datasource.username=postgres
spring.datasource.password=Aa71*17il
spring.jpa.hibernate.ddl-auto=update
